Update bulk-rename

diff --git a/bulk-rename b/bulk-rename
--- a/bulk-rename
+++ b/bulk-rename
@@ -3,7 +3,7 @@ set -euo pipefail
 
 fnd=' '; rpl='_'; dir=${1-${PWD}}
 
-[[ ! -d ${dir} || ! -O ${dir} ]] && printf 'error with %q\n' "${dir}" >&2 && exit
+[[ ! -d ${dir} || ! -O ${dir} ]] && printf 'error with %q\n' "${dir}" >&2 && exit 1
 [[ ${dir:0:1} != '/' ]] && dir=./${dir}
 cd -- "${dir}"
 
@@ -28,6 +28,7 @@ for fd in ./**/*"${fnd}"*; do
 		fname=${fd##*/}
 		fpath=${fd%/*}
 		newf=${fpath}/${fname//${fnd}/${rpl}}
+		[[ -e "${newf}" ]] && printf '%q already exists.. quitting\n' "${newf}" >&2 && exit 1
 		mv -- "${fd}" "${newf}"
 	fi
 done
@@ -39,5 +40,6 @@ for d in "${qsort_res[@]}"; do
 	dname=${d##*/}
 	dpath=${d%/*}
 	newd=${dpath}/${dname//${fnd}/${rpl}}
-	[[ ! -e "${newd}" ]] && mv -- "${d}" "${newd}"
+	[[ -e "${newd}" ]] && printf '%q already exists.. quitting\n' "${newd}" >&2 && exit 1
+	mv -- "${d}" "${newd}"
 done
